#!groovy

// Generated by IBM TransformationAdvisor
// Mon Dec 03 21:29:41 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebsphere'
    mvnCommands = '--version'
    test='false'
}